
schema {
  query: Query
}

type Query {
  testNonNull(id: string!): Droid!
  test(id: string): Droid
}


type Droid {
    nullable: Episode
    nonnullable: Episode!
}

enum Episode {
  NEWHOPE
  EMPIRE
  JEDI
}